name: Security CI/CD

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      project_name:
        description: 'Dependency Tracker Project Name'
        required: true
      project_version:
        description: 'Project Version'
        required: true

jobs:
  dependency-track:
    runs-on: ubuntu-latest  # Use a standard runner

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Clone @cyclonedx/cli repository
        run: |
          git clone https://github.com/CycloneDX/cyclonedx-node-module.git node_modules/@cyclonedx/cli

      - name: Set Project Name and Version
        run: |
          echo "Setting Project Name and Version"
          echo "PROJECT_NAME=${{ github.event.inputs.project_name }}" >> $GITHUB_ENV
          echo "PROJECT_VERSION=${{ github.event.inputs.project_version }}" >> $GITHUB_ENV

      - name: Generate SBOM
        run: pnpx cyclonedx-bom --package-manager pnpm --input ./pnpm-lock.yaml --output bom.json
      - name: Display BOM contents
        run: |
          cat bom.json
          
      - name: Check if project exists
        id: check_project
        run: |
          source $GITHUB_ENV
          RESPONSE=$(curl -s -X GET "http://deptracker-dependency-track-api-server.deptracker.svc.cluster.local/api/v1/project?name=${PROJECT_NAME}" -H "X-Api-Key: ${{ secrets.DT_ACCESS_API_KEY }}")
          if echo "$RESPONSE" | grep -q '"name":"${PROJECT_NAME}"'; then
            echo "Project exists"
            echo "::set-output name=project_exists::true"
          else
            echo "Project does not exist"
            echo "::set-output name=project_exists::false"
          fi

      - name: Create project if not exists
        if: steps.check_project.outputs.project_exists == 'false'
        run: |
          source $GITHUB_ENV
          curl -s -X PUT "http://deptracker-dependency-track-api-server.deptracker.svc.cluster.local/api/v1/project" \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: ${{ secrets.DT_ACCESS_API_KEY }}" \
            -d '{
              "name": "'"${PROJECT_NAME}"'",
              "version": "'"${PROJECT_VERSION}"'"
            }'

      - name: Upload SBOM to Dependency-Track
        run: |
          source $GITHUB_ENV
          curl -X POST "http://deptracker-dependency-track-api-server.deptracker.svc.cluster.local/api/v1/bom" \
            -H 'Content-Type: multipart/form-data' \
            -H 'X-Api-Key: ${{ secrets.DT_ACCESS_API_KEY }}' \
            -F "autoCreate=true" \
            -F "projectName=${PROJECT_NAME}" \
            -F "projectVersion=${PROJECT_VERSION}" \
            -F "bom=@sbom.json"
