name: Node.js CI/CD

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  dependency-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --silent

      - name: Generate SBOM
        run: npm audit --json > bom.json
      - name: echo sbom
        run: cat bom.json
        
      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X POST "http://forlearning.online/api/v1/bom" \
            -H 'Content-Type: multipart/form-data' \
            -H 'X-Api-Key: odt_Evt2kmmVxL2fJAjpt8ras3B2MZ6yTe5X' \
            -F "project=485456e3-d1f4-4226-a7e2-3c9230ef9c73" \
            -F "bom=@sbom.json"
