name: Node.js CI/CD

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install
      - run: npm test

  dependency-track:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14.16'

        - name: Install dependencies
          run: |
            npm install --silent

        - name: Generate SBOM
          run: npm run sbom

        - name: Upload SBOM to Dependency Track
          run: |
            curl --location --request POST 'http://35.222.227.149:8080/api/dashboard' \
            -H 'Content-Type: multipart/form-data' \
            -H 'X-Api-Key: $DEPENDENCY_TRACK_API_KEY' \
            -F 'project=$PROJECT_UUID' \
            -F 'bom=@./bom.json'

        - name: Create or Update Project in Dependency Track
          run: |
            curl --location --request POST 'https://dependency-tracker.mydomain.com/api/v1/project' \
            -H 'X-Api-Key: $DEPENDENCY_TRACK_API_KEY' \
            -H 'Content-Type: application/json' \
            --data-raw '{
              "uuid": "'$PROJECT_UUID'",
              "name": "project name",
              "version": "'$VERSION'"
            }'

        env:
          DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          PROJECT_UUID: 186cdd50-d1f4-445a-a147-a305f6571ba8
          VERSION: v1
