name: Node.js CI/CD

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  dependency-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.16'

      - name: Install dependencies
        run: npm install --silent

      - name: Generate SBOM
        run: npm audit --json > bom.json
      - name: echo sbom
        run: cat bom.json

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -v -X "POST" "http://35.222.227.149:8080/api/v1/bom" \
               -H 'Content-Type:multipart/form-data' \
               -H "X-Api-Key:LPojpCDSsEd4V9Zi6qCWr4KsiF3Konze" \
               -F "autoCreate=true" \
               -F "projectName=test" \
               -F "projectVersion=1" \
               -F "bom=@target/bom.json"
