jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install
      - run: npm test

  dependency-track:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CycloneDX CLI binary
        run: |
          curl -LO https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-cli-linux-x64.tar.gz
          tar -xzf cyclonedx-cli-linux-x64.tar.gz
          mv cyclonedx-cli-linux-x64/cyclonedx /usr/local/bin/
          chmod +x /usr/local/bin/cyclonedx
          rm -rf cyclonedx-cli-linux-x64 cyclonedx-cli-linux-x64.tar.gz
  
      - name: Generate SBOM
        run: |
          npm i --save @cyclonedx/bom
          cyclonedx -d -t application -o ./bom.json

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X POST -F "bom=@bom.json" -H "X-Api-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}" ${{ secrets.DEPENDENCY_TRACK_URL }}/api/v1/bom
        env:
          DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          DEPENDENCY_TRACK_URL: http://35.222.227.149:8080/dashboard
